# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ya:
   name: Postcommit checks
   runs-on: ubuntu-24.04
   steps:
    - uses: actions/checkout@v4
    - name: Run ya make
      run: ./third_party/yatool/ya make ./third_party/yatool --gc -r --musl
