# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ya:
   name: Postcommit checks
   continue-on-error: true
   strategy:
     fail-fast: false
     matrix:
       example: [cpp, flatbuf, go, java, protobuf, python]
   runs-on: ubuntu-24.04
   steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    # - name: Run ya make
    #   run: ./third_party/yatool/ya make ./third_party/yatool --gc -r --musl
    - name: Make examples
      run: ./third_party/yatool/ya make ./third_party/yatool/devtools/examples/tutorials/${{ matrix.example }}
    - name: Test exanmples
      run: ./third_party/yatool/ya test ./third_party/yatool/devtools/examples/tutorials/${{ matrix.example }}
