# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ya:
   name: Postcommit checks
   continue-on-error: true
   strategy:
     fail-fast: false
     matrix:
       example: [cpp, flatbuf, go, java, protobuf, python]
       build-from: [yatool, perforator]
   runs-on: ubuntu-24.04
   steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Move to repo
      if: ${{ matrix.build-from != 'yatool' }}
      run: cp -r ./third_party/yatool/devtools/examples ./third_party/${{ matrix.build-from }}/devtools
    - name: Make examples
      run: ./third_party/${{ matrix.build-from }}/ya make ./third_party/${{ matrix.build-from }}/devtools/examples/tutorials/${{ matrix.example }} -k
    - name: Test exanmples
      run: ./third_party/${{ matrix.build-from }}/ya test ./third_party/${{ matrix.build-from }}/devtools/examples/tutorials/${{ matrix.example }} -k
